import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ArrowLeft, Brain, FileText, MessageSquare, BookOpen, Download, 
  ChevronRight, Sparkles, AlertCircle, HelpCircle, Lightbulb, 
  Bookmark, CheckCircle2, Award, ArrowRight, Play, RefreshCw
} from 'lucide-react';
import { api, downloadFile } from '../lib/api.js';
import { StudyDocument, DocumentAnalysis, SmartNotes, ChatMessage, Flashcard } from '../types.js';
import { GlassCard } from './GlassCard.js';

interface DocumentViewProps {
  document: StudyDocument;
  onBack: () => void;
  onStartQuiz: (doc: StudyDocument) => void;
}

export function DocumentView({ document, onBack, onStartQuiz }: DocumentViewProps) {
  const [activeTab, setActiveTab] = useState<'analysis' | 'notes' | 'flashcards'>('analysis');
  const [activeNotesSubTab, setActiveNotesSubTab] = useState<'short' | 'detailed' | 'bullet' | 'revision'>('short');
  
  // Loading & Error States
  const [analysis, setAnalysis] = useState<DocumentAnalysis | null>(null);
  const [analysisLoading, setAnalysisLoading] = useState(true);
  const [analysisError, setAnalysisError] = useState('');
  
  const [notes, setNotes] = useState<SmartNotes | null>(null);
  const [notesLoading, setNotesLoading] = useState(true);
  const [notesError, setNotesError] = useState('');

  // Flashcards state
  const [currentFlashcardIdx, setCurrentFlashcardIdx] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  // Chat Assistant State
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [userInput, setUserInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const chatBottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setAnalysis(null);
    setNotes(null);
    setChatMessages([]);
    setUserInput('');
    setActiveTab('analysis');
    setActiveNotesSubTab('short');
    setCurrentFlashcardIdx(0);
    setIsFlipped(false);
    setAnalysisLoading(true);
    setNotesLoading(true);
    void fetchAnalysis();
    void fetchNotes();
    void fetchChatHistory();
  }, [document.id]);

  useEffect(() => {
    // Scroll chat to bottom when messages change
    chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const fetchAnalysis = async () => {
    setAnalysisLoading(true);
    setAnalysisError('');
    try {
      const data = await api.analysis.get(document.id);
      setAnalysis(data);
    } catch (err: any) {
      setAnalysisError(err.message || 'Failed to load document analysis');
    } finally {
      setAnalysisLoading(false);
    }
  };

  const fetchNotes = async () => {
    setNotesLoading(true);
    setNotesError('');
    try {
      const data = await api.notes.get(document.id);
      setNotes(data);
    } catch (err: any) {
      setNotesError(err.message || 'Failed to load smart notes');
    } finally {
      setNotesLoading(false);
    }
  };

  const fetchChatHistory = async () => {
    try {
      const data = await api.chat.getMessages(document.id);
      setChatMessages(data);
    } catch (err) {
      console.error('Failed to load chat messages:', err);
    }
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!userInput.trim() || chatLoading) return;

    const textToSend = userInput;
    setUserInput('');
    setChatLoading(true);

    // Optimistically add user message
    const tempUserMsg: ChatMessage = {
      id: Math.random().toString(),
      documentId: document.id,
      sender: 'user',
      text: textToSend,
      timestamp: new Date().toISOString()
    };
    setChatMessages(prev => [...prev, tempUserMsg]);

    try {
      const reply = await api.chat.sendMessage(document.id, textToSend);
      setChatMessages(prev => {
        const hasReply = prev.some(msg => msg.id === reply.id);
        return hasReply ? prev : [...prev, reply];
      });
    } catch (err: any) {
      const aiText = (err && err.status === 429) ? 'AI quota exceeded. Please try again later.' : (err.message || 'Failed to get response from AI assistant.');
      const tempErrorMsg: ChatMessage = {
        id: Math.random().toString(),
        documentId: document.id,
        sender: 'ai',
        text: `Error: ${aiText}`,
        timestamp: new Date().toISOString()
      };
      setChatMessages(prev => [...prev, tempErrorMsg]);
    } finally {
      setChatLoading(false);
    }
  };

  const handleDownloadNotes = () => {
    if (!notes) return;
    
    // Format smart notes as HTML printing layout
    const notesContent = `
      <h1>Smart Learning Notes: ${document.title}</h1>
      <p class="meta">Generated by StudyAI on ${new Date(notes.createdAt).toLocaleDateString()}</p>
      
      <h2>Short Notes Overview</h2>
      <p>${notes.shortNotes}</p>
      
      <h2>Detailed Academic Breakdown</h2>
      <div>${notes.detailedNotes.replace(/\n/g, '<br/>')}</div>
      
      <h2>Core Bullet Highlights</h2>
      <ul>
        ${notes.bulletNotes.map(b => `<li>${b}</li>`).join('')}
      </ul>
      
      <h2>Cram & Revision Outline</h2>
      <p>${notes.revisionNotes}</p>
      
      <h2>Flashcards Set</h2>
      <div style="margin-top: 20px;">
        ${notes.flashcards.map((f, i) => `
          <div class="card">
            <strong>Flashcard #${i + 1}</strong><br/>
            <strong>Q:</strong> ${f.question}<br/>
            <strong>A:</strong> ${f.answer}
          </div>
        `).join('')}
      </div>
    `;
    
    downloadFile(`StudyAI_Notes_${document.title.replace(/\s+/g, '_')}`, notesContent, 'html');
  };

  const handleNextCard = () => {
    if (!notes) return;
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentFlashcardIdx((prev) => (prev + 1) % notes.flashcards.length);
    }, 150);
  };

  const handlePrevCard = () => {
    if (!notes) return;
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentFlashcardIdx((prev) => (prev - 1 + notes.flashcards.length) % notes.flashcards.length);
    }, 150);
  };

  return (
    <div id="document-portal-view" className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8 select-none">
      
      {/* Top action head */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 text-left">
        <button
          id="doc-portal-back-btn"
          type="button"
          onClick={onBack}
          className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-800 dark:hover:text-white font-semibold text-sm group cursor-pointer transition-colors"
        >
          <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
          Back to Dashboard
        </button>

        <div className="flex items-center gap-2.5">
          <span className="text-xs font-bold text-slate-400 bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-white/5 px-3 py-1 rounded-full">
            Active Study Portal
          </span>
          <h2 className="text-lg font-black text-slate-800 dark:text-slate-200 truncate max-w-xs md:max-w-md">
            {document.title}
          </h2>
        </div>
      </div>

      {/* Main split grid: Study left (8 cols), chat assistant right (4 cols) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Side: Notes, summaries, and flashcards */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* Main tabs bar */}
          <div className="flex border-b border-slate-200 dark:border-white/5 p-1 bg-slate-100/50 dark:bg-slate-900/30 rounded-2xl gap-1">
            <button
              id="tab-analysis"
              onClick={() => setActiveTab('analysis')}
              className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'analysis'
                  ? 'bg-white dark:bg-[#0f0f12] text-indigo-600 dark:text-indigo-400 shadow-sm border border-slate-200/50 dark:border-white/5'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Brain className="h-4.5 w-4.5" />
              AI Analysis
            </button>
            
            <button
              id="tab-notes"
              onClick={() => setActiveTab('notes')}
              className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'notes'
                  ? 'bg-white dark:bg-[#0f0f12] text-indigo-600 dark:text-indigo-400 shadow-sm border border-slate-200/50 dark:border-white/5'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <FileText className="h-4.5 w-4.5" />
              Smart Notes
            </button>

            <button
              id="tab-flashcards"
              onClick={() => setActiveTab('flashcards')}
              className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'flashcards'
                  ? 'bg-white dark:bg-[#0f0f12] text-indigo-600 dark:text-indigo-400 shadow-sm border border-slate-200/50 dark:border-white/5'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <BookOpen className="h-4.5 w-4.5" />
              Flashcards
            </button>
          </div>

          {/* Tab Content rendering */}
          <div className="min-h-[450px]">
            <AnimatePresence mode="wait">
              
              {/* Tab 1: AI analysis breakdown */}
              {activeTab === 'analysis' && (
                <motion.div
                  key="tab-analysis-panel"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  className="space-y-6 text-left"
                >
                  {analysisLoading ? (
                    <div className="py-20 text-center space-y-4">
                      <div className="h-12 w-12 border-4 border-indigo-500/20 border-t-indigo-600 rounded-full animate-spin mx-auto" />
                      <p className="text-sm font-bold text-slate-700 dark:text-slate-300">AI is digesting your document...</p>
                      <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xs mx-auto">This takes about 10-15 seconds as we extract definitions, outline concepts, and generate exam tips.</p>
                    </div>
                  ) : analysisError ? (
                    <div className="p-8 border border-slate-200 dark:border-white/5 rounded-2xl bg-white/20 dark:bg-white/5 text-center">
                      <AlertCircle className="mx-auto h-10 w-10 text-rose-500 mb-3" />
                      <p className="text-sm font-bold text-slate-700 dark:text-slate-300">Analysis Failed</p>
                      <p className="text-xs text-slate-500 mt-2">{analysisError}</p>
                      <button onClick={fetchAnalysis} className="mt-4 px-4 py-2 bg-indigo-600 text-white font-bold rounded-xl text-xs hover:bg-indigo-700 transition">Try Again</button>
                    </div>
                  ) : analysis && (
                    <div className="space-y-6">
                      
                      {/* Document Overview Card */}
                      <GlassCard hoverEffect={false}>
                        <div className="p-6">
                          <h3 className="text-lg font-bold text-slate-950 dark:text-white flex items-center gap-2 mb-3">
                            <Sparkles className="h-5 w-5 text-indigo-500 animate-pulse" />
                            Executive Document Summary
                          </h3>
                          <p className="text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed font-normal whitespace-pre-line">
                            {analysis.summary}
                          </p>
                        </div>
                      </GlassCard>

                      {/* Side by side concepts & definitions */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        
                        {/* Key concepts */}
                        <div className="space-y-4">
                          <h4 className="text-sm font-black uppercase tracking-wider text-slate-400 flex items-center gap-1.5 px-1">
                            <Brain className="h-4 w-4 text-indigo-400" /> Key Study Concepts
                          </h4>
                          {analysis.keyConcepts.map((item, idx) => (
                            <GlassCard key={idx} hoverEffect={true} animate={false} className="border-slate-200/40 dark:border-white/5">
                              <div className="p-5">
                                <h5 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                                  <span className="h-2 w-2 rounded-full bg-indigo-500" />
                                  {item.concept}
                                </h5>
                                <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed whitespace-pre-line">
                                  {item.explanation}
                                </p>
                              </div>
                            </GlassCard>
                          ))}
                        </div>

                        {/* Definitions */}
                        <div className="space-y-4">
                          <h4 className="text-sm font-black uppercase tracking-wider text-slate-400 flex items-center gap-1.5 px-1">
                            <Bookmark className="h-4 w-4 text-purple-400" /> Core Vocabulary & Terms
                          </h4>
                          {analysis.importantDefinitions.map((item, idx) => (
                            <GlassCard key={idx} hoverEffect={true} animate={false} className="border-slate-200/40 dark:border-white/5">
                              <div className="p-5">
                                <h5 className="text-sm font-bold text-indigo-600 dark:text-indigo-400 flex items-center gap-1.5">
                                  <Lightbulb className="h-4 w-4 shrink-0" />
                                  {item.term}
                                </h5>
                                <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed whitespace-pre-line">
                                  {item.definition}
                                </p>
                              </div>
                            </GlassCard>
                          ))}
                        </div>

                      </div>

                      {/* Chapter-wise breakdown */}
                      <div className="space-y-4">
                        <h4 className="text-sm font-black uppercase tracking-wider text-slate-400 px-1">
                          Logical Chapter Breakdown
                        </h4>
                        <div className="grid grid-cols-1 gap-4">
                          {analysis.chapterSummaries.map((ch, idx) => (
                            <GlassCard key={idx} animate={false}>
                              <div className="p-5 flex flex-col md:flex-row md:items-start gap-4">
                                <div className="p-2 bg-slate-100 dark:bg-[#0f0f12] border border-slate-200 dark:border-white/5 rounded-xl font-bold text-xs text-slate-600 dark:text-slate-400 shrink-0 uppercase tracking-widest text-center w-20">
                                  Sec {idx + 1}
                                </div>
                                <div className="text-left">
                                  <h5 className="text-sm font-bold text-slate-900 dark:text-white">{ch.chapterTitle}</h5>
                                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-1.5 leading-relaxed whitespace-pre-line">{ch.summaryText}</p>
                                </div>
                              </div>
                            </GlassCard>
                          ))}
                        </div>
                      </div>

                      {/* Exam Cram Highlights */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        
                        {/* Important points */}
                        <GlassCard hoverEffect={false}>
                          <div className="p-5 text-left">
                            <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-1.5 mb-3 border-b border-slate-100 dark:border-white/5 pb-2.5">
                              <CheckCircle2 className="h-4.5 w-4.5 text-emerald-500" /> High-Yield Points
                            </h4>
                            <ul className="space-y-2.5">
                              {analysis.importantPoints.map((pt, i) => (
                                <li key={i} className="text-xs text-slate-600 dark:text-slate-400 flex items-start gap-2 leading-relaxed">
                                  <span className="text-emerald-500 font-bold mt-0.5">•</span>
                                  <span>{pt}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </GlassCard>

                        {/* Exam tips */}
                        <GlassCard hoverEffect={false}>
                          <div className="p-5 text-left">
                            <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-1.5 mb-3 border-b border-slate-100 dark:border-white/5 pb-2.5">
                              <Award className="h-4.5 w-4.5 text-amber-500 animate-pulse" /> AI Exam Strategies
                            </h4>
                            <ul className="space-y-2.5">
                              {analysis.examTips.map((tip, i) => (
                                <li key={i} className="text-xs text-slate-600 dark:text-slate-400 flex items-start gap-2 leading-relaxed">
                                  <span className="text-amber-500 font-black mt-0.5">★</span>
                                  <span>{tip}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </GlassCard>

                      </div>

                    </div>
                  )}
                </motion.div>
              )}

              {/* Tab 2: Smart Study Notes Tab */}
              {activeTab === 'notes' && (
                <motion.div
                  key="tab-notes-panel"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  className="space-y-6 text-left"
                >
                  {notesLoading ? (
                    <div className="py-20 text-center space-y-4">
                      <div className="h-12 w-12 border-4 border-purple-500/20 border-t-purple-600 rounded-full animate-spin mx-auto" />
                      <p className="text-sm font-bold text-slate-700 dark:text-slate-300">Generating study notes set...</p>
                      <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xs mx-auto">We are organizing summaries, creating bullet-point cram outlines, and formulating flashcards.</p>
                    </div>
                  ) : notesError ? (
                    <div className="p-8 border border-slate-200 dark:border-white/5 rounded-2xl bg-white/20 dark:bg-white/5 text-center">
                      <AlertCircle className="mx-auto h-10 w-10 text-rose-500 mb-3" />
                      <p className="text-sm font-bold text-slate-700 dark:text-slate-300">Notes Generation Failed</p>
                      <p className="text-xs text-slate-500 mt-2">{notesError}</p>
                      <button onClick={fetchNotes} className="mt-4 px-4 py-2 bg-indigo-600 text-white font-bold rounded-xl text-xs hover:bg-indigo-700 transition">Try Again</button>
                    </div>
                  ) : notes && (
                    <div className="space-y-6">
                      
                      {/* Sub tab actions bar for Notes formats */}
                      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 dark:border-white/5 pb-3">
                        <div className="flex gap-1 bg-slate-100 dark:bg-[#0f0f12] rounded-xl p-1 shrink-0">
                          <button
                            onClick={() => setActiveNotesSubTab('short')}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                              activeNotesSubTab === 'short' 
                                ? 'bg-white dark:bg-[#0a0a0c] text-indigo-600 dark:text-indigo-400 shadow-sm' 
                                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                            }`}
                          >
                            Short
                          </button>
                          <button
                            onClick={() => setActiveNotesSubTab('detailed')}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                              activeNotesSubTab === 'detailed' 
                                ? 'bg-white dark:bg-[#0a0a0c] text-indigo-600 dark:text-indigo-400 shadow-sm' 
                                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                            }`}
                          >
                            Detailed
                          </button>
                          <button
                            onClick={() => setActiveNotesSubTab('bullet')}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                              activeNotesSubTab === 'bullet' 
                                ? 'bg-white dark:bg-[#0a0a0c] text-indigo-600 dark:text-indigo-400 shadow-sm' 
                                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                            }`}
                          >
                            Bullets
                          </button>
                          <button
                            onClick={() => setActiveNotesSubTab('revision')}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                              activeNotesSubTab === 'revision' 
                                ? 'bg-white dark:bg-[#0a0a0c] text-indigo-600 dark:text-indigo-400 shadow-sm' 
                                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                            }`}
                          >
                            Revision
                          </button>
                        </div>

                        {/* Download notes PDF action */}
                        <button
                          id="download-notes-pdf-btn"
                          onClick={handleDownloadNotes}
                          className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-md shadow-indigo-600/10 cursor-pointer transition-all shrink-0"
                        >
                          <Download className="h-4 w-4" />
                          Download Notes (PDF)
                        </button>
                      </div>

                      {/* Render notes content based on subtab */}
                      <GlassCard hoverEffect={false}>
                        <div className="p-6 md:p-8">
                          {activeNotesSubTab === 'short' && (
                            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                              <h3 className="text-xl font-extrabold text-slate-950 dark:text-white">Short Summary Notes</h3>
                              <p className="text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed whitespace-pre-line font-normal">
                                {notes.shortNotes}
                              </p>
                            </motion.div>
                          )}

                          {activeNotesSubTab === 'detailed' && (
                            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                              <h3 className="text-xl font-extrabold text-slate-950 dark:text-white">In-Depth Academic Breakdowns</h3>
                              <div className="text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed whitespace-pre-line font-normal">
                                {notes.detailedNotes}
                              </div>
                            </motion.div>
                          )}

                          {activeNotesSubTab === 'bullet' && (
                            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                              <h3 className="text-xl font-extrabold text-slate-950 dark:text-white">Bullet point summary sheets</h3>
                              <ul className="space-y-3.5">
                                {notes.bulletNotes.map((bullet, i) => (
                                  <li key={i} className="text-slate-700 dark:text-slate-300 text-sm flex items-start gap-3">
                                    <span className="h-6 w-6 rounded-lg bg-indigo-50 dark:bg-indigo-950/40 border border-indigo-200/50 dark:border-indigo-500/10 text-indigo-600 dark:text-indigo-400 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">{i+1}</span>
                                    <span className="mt-0.5 leading-relaxed">{bullet}</span>
                                  </li>
                                ))}
                              </ul>
                            </motion.div>
                          )}

                          {activeNotesSubTab === 'revision' && (
                            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                              <h3 className="text-xl font-extrabold text-slate-950 dark:text-white">Condense Revision Study List</h3>
                              <p className="text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed whitespace-pre-line font-normal">
                                {notes.revisionNotes}
                              </p>
                            </motion.div>
                          )}
                        </div>
                      </GlassCard>

                    </div>
                  )}
                </motion.div>
              )}

              {/* Tab 3: Interactive Flashcards */}
              {activeTab === 'flashcards' && (
                <motion.div
                  key="tab-flashcards-panel"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  className="space-y-6 text-center"
                >
                  {notesLoading ? (
                    <div className="py-20 text-center space-y-4">
                      <div className="h-12 w-12 border-4 border-indigo-500/20 border-t-indigo-600 rounded-full animate-spin mx-auto" />
                      <p className="text-sm font-bold text-slate-700 dark:text-slate-300">Formulating active-recall flashcards...</p>
                    </div>
                  ) : notesError ? (
                    <div className="p-8 border rounded-2xl bg-white/20 text-center">
                      <p className="text-sm font-bold">Failed to load flashcards.</p>
                    </div>
                  ) : notes && notes.flashcards.length > 0 ? (
                    <div className="max-w-md mx-auto space-y-8 py-6">
                      
                      <div className="flex justify-between items-center px-1">
                        <span className="text-xs font-bold text-slate-400">
                          Flashcard {currentFlashcardIdx + 1} of {notes.flashcards.length}
                        </span>
                        <span className="text-xs font-black text-indigo-500 uppercase tracking-widest flex items-center gap-1">
                          <Brain className="h-3.5 w-3.5" /> Active Recall Study
                        </span>
                      </div>

                      {/* Interactive Flip Card Stage */}
                      <div 
                        id="flashcard-stage-container"
                        onClick={() => setIsFlipped(!isFlipped)}
                        className="h-64 w-full cursor-pointer relative preserve-3d group perspective-1000"
                      >
                        <motion.div
                          animate={{ rotateY: isFlipped ? 180 : 0 }}
                          transition={{ duration: 0.4, ease: 'easeOut' }}
                          className="w-full h-full relative transform-style-3d duration-500"
                        >
                          {/* FRONT SIDE */}
                          <div className={`absolute inset-0 w-full h-full rounded-2xl border border-slate-200/50 dark:border-white/5 bg-white dark:bg-[#0f0f12] p-6 flex flex-col justify-between items-center text-center shadow-xl backface-hidden ${isFlipped ? 'pointer-events-none' : ''}`}>
                            <div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Question</div>
                            <p className="text-base md:text-lg font-extrabold text-slate-900 dark:text-white px-2 leading-relaxed">
                              {notes.flashcards[currentFlashcardIdx].question}
                            </p>
                            <div className="text-[11px] font-bold text-indigo-500 dark:text-indigo-400 flex items-center gap-1.5 bg-indigo-500/10 px-3 py-1 rounded-full border border-indigo-500/15 animate-pulse">
                              <RefreshCw className="h-3 w-3" /> Click card to flip
                            </div>
                          </div>

                          {/* BACK SIDE */}
                          <div className={`absolute inset-0 w-full h-full rounded-2xl border border-slate-200/50 dark:border-white/5 bg-indigo-50 dark:bg-slate-900/40 p-6 flex flex-col justify-between items-center text-center shadow-xl backface-hidden [transform:rotateY(180deg)] ${!isFlipped ? 'pointer-events-none' : ''}`}>
                            <div className="text-[10px] font-black uppercase tracking-widest text-indigo-500 dark:text-indigo-400">Answer Explanation</div>
                            <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 px-2 leading-relaxed whitespace-pre-line">
                              {notes.flashcards[currentFlashcardIdx].answer}
                            </p>
                            <div className="text-[10px] font-bold text-emerald-500 flex items-center gap-1">
                              <CheckCircle2 className="h-4 w-4" /> Got it! Click to flip back
                            </div>
                          </div>

                        </motion.div>
                      </div>

                      {/* Card Navigation Controls */}
                      <div className="flex justify-between items-center">
                        <button
                          id="flashcard-prev-btn"
                          onClick={handlePrevCard}
                          className="px-4 py-2 border border-slate-200 dark:border-white/5 hover:bg-slate-100 dark:hover:bg-white/5 rounded-xl text-xs font-bold text-slate-600 dark:text-slate-400 cursor-pointer transition-colors"
                        >
                          Previous Card
                        </button>
                        
                        <button
                          id="flashcard-next-btn"
                          onClick={handleNextCard}
                          className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-md shadow-indigo-600/15 cursor-pointer transition-all"
                        >
                          Next Card
                        </button>
                      </div>

                    </div>
                  ) : (
                    <div className="p-8 text-center text-slate-500">
                      No flashcards available. Please upload reference material.
                    </div>
                  )}
                </motion.div>
              )}

            </AnimatePresence>
          </div>

          {/* Quick Quiz Box recommendation */}
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onStartQuiz(document);
            }}
            className="w-full text-left"
          >
            <GlassCard hoverEffect={true} className="border-purple-500/20 bg-purple-500/5">
              <div className="p-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-left">
                <div className="space-y-1">
                  <h4 className="text-base font-extrabold text-slate-950 dark:text-white flex items-center gap-2">
                    <Award className="h-5 w-5 text-purple-500 animate-pulse" />
                    Ready to test your memory?
                  </h4>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-normal font-medium max-w-lg">
                    Generate a customized practice test based *only* on the text from this document. Choose multiple choice, true/false, fill-in-the-blanks, or custom short questions.
                  </p>
                </div>

                <div className="inline-flex items-center gap-1.5 bg-purple-600 hover:bg-purple-700 text-white px-4 py-2.5 rounded-xl text-xs font-bold shadow-md shadow-purple-600/10 transition-all shrink-0">
                  Generate Test
                  <ArrowRight className="h-4 w-4" />
                </div>
              </div>
            </GlassCard>
          </button>

        </div>

        {/* Right Side: Floating AI Chat Assistant grounded strictly in document */}
        <div className="lg:col-span-4 h-full">
          <GlassCard hoverEffect={false} className="border-slate-200/50 dark:border-white/5 h-[640px] flex flex-col justify-between">
            <div className="p-4 border-b border-slate-100 dark:border-white/5 flex items-center justify-between shrink-0 text-left">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 rounded-xl">
                  <MessageSquare className="h-4.5 w-4.5 animate-pulse" />
                </div>
                <div>
                  <h4 className="text-xs font-black text-slate-900 dark:text-white leading-none">Document Chat Tutor</h4>
                  <p className="text-[10px] text-slate-400 mt-1 uppercase font-semibold leading-none">Strict Grounding Mode</p>
                </div>
              </div>
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" title="Ready to assist" />
            </div>

            {/* Chat Messages display */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3.5 scrollbar-thin max-h-[460px]">
              {chatMessages.length === 0 ? (
                <div className="h-full flex flex-col justify-center items-center text-center p-6 space-y-3">
                  <div className="p-3 bg-slate-100 dark:bg-slate-900 text-slate-400 rounded-full border border-slate-200 dark:border-white/5">
                    <MessageSquare className="h-6 w-6" />
                  </div>
                  <p className="text-xs font-bold text-slate-700 dark:text-slate-300">Ask any question about this file</p>
                  <p className="text-[10px] text-slate-400 dark:text-slate-500 max-w-xs leading-normal">
                    Examples: "Explain the main subject", "Define key vocabulary terms in simpler words", "Give me a practical analogy of page 1".
                  </p>
                </div>
              ) : (
                chatMessages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'} text-left`}
                  >
                    <div
                      className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-xs font-medium leading-relaxed whitespace-pre-line ${
                        msg.sender === 'user'
                          ? 'bg-indigo-600 text-white rounded-br-none shadow-md shadow-indigo-600/5 border border-indigo-500/10'
                          : 'bg-slate-100/80 dark:bg-slate-900/80 text-slate-800 dark:text-slate-200 border border-slate-200/40 dark:border-white/5 rounded-bl-none shadow-inner'
                      }`}
                    >
                      {msg.text}
                    </div>
                  </div>
                ))
              )}
              
              {chatLoading && (
                <div className="flex justify-start text-left">
                  <div className="bg-slate-100 dark:bg-[#0f0f12] border border-slate-200/30 dark:border-white/5 rounded-2xl rounded-bl-none px-4 py-3 text-xs flex items-center gap-2">
                    <span className="text-slate-500 font-bold">AI tutor is writing</span>
                    <div className="flex gap-1">
                      <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce [animation-delay:-0.3s]" />
                      <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce [animation-delay:-0.15s]" />
                      <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce" />
                    </div>
                  </div>
                </div>
              )}
              <div ref={chatBottomRef} />
            </div>

            {/* Chat input box */}
            <form
              onSubmit={handleSendMessage}
              onClick={(e) => e.stopPropagation()}
              className="p-3 bg-slate-50 dark:bg-[#0a0a0c] border-t border-slate-100 dark:border-white/5 shrink-0"
            >
              <div className="relative flex items-center">
                <input
                  id="chat-user-input"
                  type="text"
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  placeholder="Ask a question about this material..."
                  className="w-full bg-white dark:bg-[#0f0f12] border border-slate-200 dark:border-white/5 text-slate-900 dark:text-white rounded-xl py-3 pl-4 pr-12 text-xs font-medium focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400"
                />
                <button
                  id="chat-send-btn"
                  type="submit"
                  disabled={!userInput.trim() || chatLoading}
                  className="absolute right-2 p-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                >
                  <ArrowRight className="h-4 w-4" />
                </button>
              </div>
            </form>
          </GlassCard>
        </div>

      </div>

    </div>
  );
}
